---

- name: Create namespace for core resources
  kubernetes.core.k8s:
    name: core
    api_version: v1
    kind: Namespace
    state: present

- name: Create local image registry
  kubernetes.core.k8s:
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: image-registry
        namespace: core
      spec:
        selector:
          matchLabels:
            app: image-registry
        template:
          metadata:
            labels:
              app: image-registry
          spec:
            containers:
            - name: registry
              image: registry:2
              ports:
              - containerPort: 5000

- name: Expose image registry
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: image-registry
        namespace: core
      spec:
        type: LoadBalancer
        selector:
          app: image-registry
        ports:
        - port: 5000
          targetPort: 5000
          nodePort: 30000
          protocol: TCP

- name: Copy registries.yaml
  ansible.builtin.copy:
    src: files/registries.yaml
    dest: /etc/rancher/k3s/registries.yaml
    owner: root
    group: root
    mode: '0644'

- name: Reload k3s
  ansible.builtin.systemd_service:
    name: k3s.service
    state: restarted

- name: Copy daemon.json
  ansible.builtin.copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'

- name: Reload Docker
  ansible.builtin.systemd_service:
    name: docker.service
    state: restarted

- name: Build an image and push it to a private repo 
  community.docker.docker_image: 
    build: 
      path: templates 
    name: "100.65.4.54:30000/scorechecker" 
    tag: v1 
    force_tag: true 
    push: true 
    source: build 

